[tasks.test]
description = "Run all co2 compiletests"
run = "cargo run -q --locked -p co2_test_harness"

[tasks.test-ui]
description = "Run compiletests under the ui directory"
run = "cargo run -q --locked -p co2_test_harness -- 'tests/compiletest/ui/**'"

[tasks.test-run]
description = "Run compiletests under the run directory"
run = "cargo run -q --locked -p co2_test_harness -- 'tests/compiletest/run/**'"
